[ESPv2] Use any stable gke release, don't pin to 1.14
Just `release/stable` should work:

https://github.com/kubernetes/test-infra/blob/fd124b768d9e95177125c6f3d19b3af8b5e71a03/kubetest/extract_k8s.go#L49

Fixes all the test failures currently due to GKE not supporting 1.14:

```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=No valid versions with the prefix "1.14.10" found.
```

Signed-off-by: Teju Nareddy <nareddyt@google.com>